teleop_twist_joy_node:
  ros__parameters:
    enable_button: 0                # Move without needing to hold any button
    enable_turbo_button: 5          # RB (optional turbo mode)

    axis_linear.x: 1                # Left stick vertical for forward/backward
    scale_linear.x: 3.0
    scale_linear_turbo.x: 1.0

    axis_angular.yaw: 2             # Right stick horizontal for steering
    scale_angular.yaw: 1.0
    scale_angular_turbo.yaw: 1.8
